### ISSUE TITLE
webmin not starting 

### ISSUE THREAD

**Issue by sojab0on** [jesinmat/tkl-gameserver#17]
Hi i installed the lxc container tamplate for the gmaeserver in console of proxomox it runs fine but i cant reach webmin 

when i run journalctl -xe it states 

Mar 12 09:59:02 GS01 systemd[1]: stunnel4@webmin.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Automatic restarting of the unit stunnel4@webmin.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mar 12 09:59:02 GS01 systemd[1]: Stopped Universal SSL tunnel for network daemons (webmin).
-- Subject: A stop job for unit stunnel4@webmin.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit stunnel4@webmin.service has finished.
-- 
-- The job identifier is 2298 and the job result is done.
Mar 12 09:59:02 GS01 systemd[1]: stunnel4@webmin.service: Start request repeated too quickly.
Mar 12 09:59:02 GS01 systemd[1]: stunnel4@webmin.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit stunnel4@webmin.service has entered the 'failed' state with result 'exit-code'.
Mar 12 09:59:02 GS01 systemd[1]: Failed to start Universal SSL tunnel for network daemons (webmin).
-- Subject: A start job for unit stunnel4@webmin.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit stunnel4@webmin.service has finished with a failure.
-- 
-- The job identifier is 2298 and the job result is failed.

**Comment by jesinmat** [comment]
Hello, please put this issue to the official TurnKey Gameserver repo https://github.com/turnkeylinux-apps/gameserver - they maintain this image now. In addition to that, they are many commits ahead, so the issue might be fixed already.
